### PR TITLE
logger:

### PR DESCRIPTION
**Pull request by piiiet**
compacted init_log()

code was tested successfully for
- /logs creation, if not existing
- streembit.log creation, if not existing
- streembit.log renaming, if existing

TODO:
create unit tests

### CODE REVIEW

**Comment by zsoltpardi** [comment]
I haven't tested it, but taking a look at the code I realized the original code was incorrect and the PR keeps the incorrect code. This line is not correct and does not make sense in the original code (which I wrote):

var logspath = logdir || path.join(process.cwd(), logsdir)

If the logdir does not exists then the path.join shouldn't try to use the "logsdir" variable as it is never initialized. I think in the past we had a "logsdir" variable initialized somewhere, but it was removed but the variable is still used, which is incorrect.

**Comment by piiiet** [comment]
you're right
refactored that

**Comment by zsoltpardi** [comment]
The problem is, we would still need a validation for the "logdir" variable. Before the "logdir ||" was attempting to handle the scenario when the logdir is empty (of course that was not correct because of the never initialized "logsdir" variable). So I think we would still need to make sure the "logdir" variable is populated by taking the current process directory plus the "logs" subdirectory if there is an empty "logdir" was passed to the init_log function.

**Comment by piiiet** [comment]
added handling for empty logdir:
set logdir to "/logs", if logdir is in [undefined, null, ""]

**Pull request merged**
